# ###Receipt Create
# POST http://localhost:3000/receipts/process
# Content-Content-Type: application/json

# {
# "retailer": "Target",
# "purchased_at": "",
# "total_cents": "",
# "unique_id": ""
# }